### ISSUE TITLE
Agree (Opt-in)

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-ios-privacy-dashboard#4]
It is possible to agree, opt-in, or sign a consent agreement.

- [x] decentralised-dataexchange/bb-consent-ios-privacy-dashboard/issues/25
- [x] decentralised-dataexchange/bb-consent-ios-privacy-dashboard/issues/26
- [x] decentralised-dataexchange/bb-consent-ios-privacy-dashboard/issues/15
